# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/hm-Private/GZCF/main/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# 订阅链接
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/shadowsocks

# 订阅链接
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/shadowsocksR

# 订阅链接
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/v2ray

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ss/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/sip002/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ssr/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/vmess/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/trojan/sub

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://52bp.org/freesite.html

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://view.freev2ray.org/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://free-ss.site/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://lncn.org/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://3.weiwei.in/2020.html

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
