# 模糊抓取订阅链接
- type: clash
  options:
    url: https://sub.sub.cm/sub?target=clash&url=http%3A%2F%2F106.15.251.133%3A54321%2Fclash%2Fproxies&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full.ini&emoji=false&list=true&udp=false&tfo=false&scv=false&fdn=false&sort=false&new_name=true
