# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/hm-Private/GZCF/main/sub.list

# 订阅链接
- type: clash
  options:
    url: https://proxypoolss.tk/ss/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolss.tk/sip002/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolss.tk/ssr/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolss.tk/vmess/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolss.tk/trojan/sub

# 订阅链接
- type: clash
  options:
    url: https://proxypool.ga/ss/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypool.ga/sip002/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypool.ga/ssr/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypool.ga/vmess/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypool.ga/trojan/sub

# 订阅链接
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/shadowsocks

# 订阅链接
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/shadowsocksR

# 订阅链接
- type: subscribe
  options:
    url: http://proxypool.turinglabs.net/upload/daily/v2ray

# 订阅链接
- type: clash
  options:
    url: https://proxypoolsstest.herokuapp.com/ss/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/sip002/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ssr/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/vmess/sub

# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/trojan/sub

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/v2

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/ssr


# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/trojan

# 杂乱订阅区

# 订阅链接
- type: subscribe
  options:
    url: https://suda.sub.koicloud.pw/link/K9vz0uFPe9ULfdqX?sub=3

# 订阅链接
- type: subscribe
  options:
    url: https://v2.fit/modules/servers/V2raySocks/osubscribe.php?sid=7063&token=lKJwbO2onxIr

# 订阅链接
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=d309c6921bbd7d0d

# 订阅链接
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=d309c6921bbd7d0d

# 订阅链接
- type: subscribe
  options:
    url: https://qiaomenzhuanfx.netlify.app/

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/satrom/V2SSR/master/V2RAY/Sub.txt

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/hotsymbol/vpnsetting/master/v2rayopen

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/satrom/V2SSR/master/SSR/Day.txt

# 订阅链接
- type: subscribe
  options:
    url: https://youlianboshi.netlify.app/

# 订阅链接
- type: subscribe
  options:
    url: https://iwxf.netlify.app/

# 订阅链接
- type: subscribe
  options:
    url: https://jiang.netlify.app/

# 订阅链接
- type: subscribe
  options:
    url: https://qiaomenzhuanfx.netlify.app/

# 订阅链接
- type: subscribe
  options:
    url: https://muma16fx.netlify.app/

# 订阅链接
- type: subscribe
  options:
    url: http://ss.pythonic.life/full/subscribe

# 订阅链接
- type: subscribe
  options:
    url: https://bit.ly/2D5fWhX

# 订阅链接
- type: subscribe
  options:
    url: https://prom-php.herokuapp.com/cloudfra_ssr.txt

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/online

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/RaymondHarris971/ssrsub/master/9a075bdee5.txt

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/20200808.txt

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/satrom/V2SSR/master/SSR/Sub.txt

# 订阅链接
- type: subscribe
  options:
    url: https://shadow-socks-share.herokuapp.com/subscribe

# 订阅链接
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=DAYxR3mMaZAsaqUb

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/cdp2020/v2ray/master/README.md

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://www.lanxh.com/category/ziyuan

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://fanqiang.network/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://www.freess.best/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://zhimianfei.com/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://lightyearvpn.com/zh/free-vpn

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://52bp.org/freesite.html

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://www.youneed.win/free-ssr

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://zfjvpn.gitbook.io/123/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://view.freev2ray.org/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://free-ss.site/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://lncn.org/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://3.weiwei.in/2020.html

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# 网页模糊抓取
- type: webfuzz
  options:
    url: http://www.younglass.com/nodelist

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrv2jiedian
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrshares
    num: 200

# 翻墙党论坛抓取
- type: webfuzz
  options:
    url: https://www.vpngate.net/cn/

# 翻墙党论坛抓取
- type: webfuzz
  options:
    url: https://www.freeopenvpn.org/

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0905/quan.conf

# 某个网站抓取
- type: web-freessrxyz
  options:
